apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app-front-deployment
spec:
  selector:
   matchLabels:
    app: billing-app-front
  replicas: 2
  template:
    metadata:
      labels:
        app: billing-app-front
    spec:
      containers:
        - name: billing-app-front
          image: oneri18/billingapp-frontend:0.0.1 
          ports:
            - containerPort: 80
              name: billingappfport
---
apiVersion: v1
kind: Service
metadata:
  name: billing-app-front-service
  labels:
    app: billing-app-front
spec:
  selector:
   app: billing-app-front
  type: NodePort 
  ports:
   - port: 80
     nodePort: 30100